### ISSUE TITLE
Execution failed for task ':react-native-image-filter-kit:compileDebugRenderscript'.

### ISSUE THREAD

**Issue by stepupithubapp** [iyegoroff/react-native-image-filter-kit#29] opened 2019-11-18 05:44 UTC

**Comment by stepupithubapp** [comment] 2019-11-18 05:44
A problem occurred starting process 'command '/home/stepupithub/Android/Sdk/build-tools/28.0.3/i686-linux-android-ld''

**Comment by iyegoroff** [comment] 2019-11-19 20:12
What is your OS? Looks like a duplicate of #27

**Closed** 2019-11-20 19:37 UTC
Labels: duplicate
